[package]
name = "hyperlane"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = """A lightweight, high-performance, and cross-platform Rust HTTP server library built on Tokio. It simplifies modern web service development by providing built-in support for middleware, WebSocket, Server-Sent Events (SSE), and raw TCP communication. With a unified and ergonomic API across Windows, Linux, and MacOS, it enables developers to build robust, scalable, and event-driven network applications with minimal overhead and maximum flexibility."""
keywords = ["http", "request", "response", "tcp", "cross-platform"]
repository.workspace = true
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[workspace.package]
version = "21.5.0"
readme = "README.md"
edition = "2024"
authors = ["root@ltpp.vip"]
license = "MIT"
repository = "https://github.com/hyperlane-dev/hyperlane.git"
exclude = ["target", "Cargo.lock", "sh", ".github", "logs", "img", "**/*.log"]

[workspace]
resolver = "2"
members = ["core", "macros", "type", "cli", "request", "constant", "compress"]

[workspace.dependencies]
hyperlane-cli = { path = "cli" }
hyperlane-core = { path = "core" }
hyperlane-type = { path = "type" }
http-compress = { path = "compress" }
http-constant = { path = "constant" }
http-request = { path = "request" }
hyperlane-macros = { path = "macros" }

hex = "0.4.3"
url = "2.5.8"
log = "0.4.34"
toml = "0.9.8"
which = "8.0.6"
brotli = "9.0.0"
flate2 = "1.1.10"
quote = "1.0.47"
regex = "1.13.1"
futures = "0.3.33"
twox-hash = "2.1.4"
http-type = "20.1.9"
inventory = "0.3.24"
thiserror = "2.0.21"
serde-xml-rs = "0.8.2"
serde_json = "1.0.151"
tungstenite = "0.30.0"
webpki-roots = "1.0.9"
proc-macro2 = "1.0.107"
color-output = "10.0.10"
lombok-macros = "2.1.0"
serde_urlencoded = "0.7.1"
tokio-tungstenite = "0.30.0"
syn = { version = "3.0.6", features = ["full"] }
tokio = { version = "1.53.1", features = ["full"] }
serde = { version = "1.0.229", features = ["derive"] }
notify = { version = "8.2.0", default-features = false, features = [
    "macos_fsevent",
] }
rustls = { version = "0.23.45", default-features = false, features = [
    "ring",
    "tls12",
] }
tokio-rustls = { version = "0.26.5", default-features = false, features = [
    "ring",
    "tls12",
] }

[dependencies]
hyperlane-core = { workspace = true }
hyperlane-macros = { workspace = true }

[profile.dev]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
