[package]
name = "hyperlane-cli"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """A command-line tool for Hyperlane framework."""
keywords = ["output", "console", "log", "print", "color"]
categories = ["command-line-interface", "development-tools", "visualization"]
exclude.workspace = true

[[bin]]
name = "hyperlane"
path = "src/main.rs"

[dependencies]
hyperlane-core = { workspace = true }
http-type = { workspace = true }
hyperlane-macros = { workspace = true }

log = { workspace = true }
tokio = { workspace = true }
notify = { workspace = true }
thiserror = { workspace = true }
color-output = { workspace = true }
lombok-macros = { workspace = true }
