[package]
name = "hyperlane-plugin-websocket"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """A WebSocket plugin for the Hyperlane framework, providing robust WebSocket communication capabilities and integrating with hyperlane-broadcast for efficient message dissemination."""
keywords = ["http", "request", "response", "tcp", "redirect"]
categories = ["network-programming", "web-programming"]
exclude.workspace = true

[dependencies]
hyperlane = { workspace = true }

tokio-broadcast = { workspace = true }
