use super::*;

/// HTTP/2 connection preface
pub const CONNECTION_PREFACE: &[u8] = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n";

/// HTTP/2 SETTINGS parameter: HEADER_TABLE_SIZE (0x1)
pub const HEADER_TABLE_SIZE: u16 = 0x1;

/// HTTP/2 SETTINGS parameter: ENABLE_PUSH (0x2)
pub const ENABLE_PUSH: u16 = 0x2;

/// HTTP/2 SETTINGS parameter: MAX_CONCURRENT_STREAMS (0x3)
pub const MAX_CONCURRENT_STREAMS: u16 = 0x3;

/// HTTP/2 SETTINGS parameter: INITIAL_WINDOW_SIZE (0x4)
pub const INITIAL_WINDOW_SIZE: u16 = 0x4;

/// HTTP/2 SETTINGS parameter: MAX_FRAME_SIZE (0x5)
pub const SETTINGS_MAX_FRAME_SIZE: u16 = 0x5;

/// HTTP/2 SETTINGS parameter: MAX_HEADER_LIST_SIZE (0x6)
pub const MAX_HEADER_LIST_SIZE: u16 = 0x6;

/// HTTP/2 pseudo-header field `:status`, used to specify the HTTP status code.
pub const COLON_STATUS: &str = ":status";

/// Accept-Encoding header value: "gzip, deflate"
pub const GZIP_DEFLATE: &str = "gzip, deflate";

/// Path value: "/index.html"
pub const INDEX_HTML_PATH: &str = "/index.html";

/// HPACK static table as defined in RFC 7541 Appendix A
pub const STATIC_TABLE: &[(&str, &str)] = &[
    (COLON_AUTHORITY, EMPTY_STR),
    (COLON_METHOD, GET),
    (COLON_METHOD, POST),
    (COLON_PATH, DEFAULT_HTTP_PATH),
    (COLON_PATH, INDEX_HTML_PATH),
    (COLON_SCHEME, HTTP_LOWERCASE),
    (COLON_SCHEME, HTTPS_LOWERCASE),
    (COLON_STATUS, STATUS_CODE_200),
    (COLON_STATUS, STATUS_CODE_204),
    (COLON_STATUS, STATUS_CODE_206),
    (COLON_STATUS, STATUS_CODE_304),
    (COLON_STATUS, STATUS_CODE_400),
    (COLON_STATUS, STATUS_CODE_404),
    (COLON_STATUS, STATUS_CODE_500),
    (ACCEPT_CHARSET, EMPTY_STR),
    (ACCEPT_ENCODING, GZIP_DEFLATE),
    (ACCEPT_LANGUAGE, EMPTY_STR),
    (ACCEPT_RANGES, EMPTY_STR),
    (ACCEPT, EMPTY_STR),
    (ACCESS_CONTROL_ALLOW_ORIGIN, EMPTY_STR),
    (AGE, EMPTY_STR),
    (ALLOW, EMPTY_STR),
    (AUTHORIZATION, EMPTY_STR),
    (CACHE_CONTROL, EMPTY_STR),
    (CONTENT_DISPOSITION, EMPTY_STR),
    (CONTENT_ENCODING, EMPTY_STR),
    (CONTENT_LANGUAGE, EMPTY_STR),
    (CONTENT_LENGTH, EMPTY_STR),
    (CONTENT_LOCATION, EMPTY_STR),
    (CONTENT_RANGE, EMPTY_STR),
    (CONTENT_TYPE, EMPTY_STR),
    (COOKIE, EMPTY_STR),
    (DATE, EMPTY_STR),
    (ETAG, EMPTY_STR),
    (EXPECT, EMPTY_STR),
    (EXPIRES, EMPTY_STR),
    (FROM, EMPTY_STR),
    (HOST, EMPTY_STR),
    (IF_MATCH, EMPTY_STR),
    (IF_MODIFIED_SINCE, EMPTY_STR),
    (IF_NONE_MATCH, EMPTY_STR),
    (IF_RANGE, EMPTY_STR),
    (IF_UNMODIFIED_SINCE, EMPTY_STR),
    (LAST_MODIFIED, EMPTY_STR),
    (LINK, EMPTY_STR),
    (LOCATION, EMPTY_STR),
    (MAX_FORWARDS, EMPTY_STR),
    (PROXY_AUTHENTICATE, EMPTY_STR),
    (PROXY_AUTHORIZATION, EMPTY_STR),
    (RANGE, EMPTY_STR),
    (REFERER, EMPTY_STR),
    (REFRESH, EMPTY_STR),
    (RETRY_AFTER, EMPTY_STR),
    (SERVER, EMPTY_STR),
    (SET_COOKIE, EMPTY_STR),
    (STRICT_TRANSPORT_SECURITY, EMPTY_STR),
    (TRANSFER_ENCODING, EMPTY_STR),
    (USER_AGENT, EMPTY_STR),
    (VARY, EMPTY_STR),
    (VIA, EMPTY_STR),
    (WWW_AUTHENTICATE, EMPTY_STR),
];
