[package]
name = "http-compress"
version.workspace = true
readme.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = """A high-performance async library for HTTP compression/decompression, supporting Brotli, Deflate, and Gzip algorithms. Provides both compression and decompression capabilities with optimized memory usage, ideal for HTTP clients/servers and network programming."""
keywords = ["http", "request", "response", "tcp", "redirect"]
categories = ["network-programming", "web-programming"]
exclude = ['**/*.log', '.github', 'Cargo.lock', 'debug', 'img', 'logs', 'sh', 'target', 'tmp']

[dependencies]
brotli = { workspace = true }
flate2 = { workspace = true }
twox-hash = { workspace = true }
